baseURL = "https://selenide.org"
title = "Selenide"
defaultContentLanguage = "en"

buildFuture = true

disableKinds = ["taxonomy", "term"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[params]
  selenideVersion = "7.16.0"
  seleniumChangelog = "https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG"
  googleAnalyticsId = "UA-39031927-1"

[params.author]
  name = "Andrei Solntsev"
  email = "andrei.solntsev@gmail.com"
  github = "asolntsev"
  twitter = "selenide"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageCode = "en"
    languageName = "English"
    weight = 1
    [languages.en.params]
      tagline = "Concise UI tests in Java"
  [languages.ru]
    contentDir = "content/ru"
    languageCode = "ru"
    languageName = "Русский"
    weight = 2
    [languages.ru.params]
      tagline = "Лаконичные и стабильные UI тесты на Java"

[permalinks]
  blog = "/:year/:month/:day/:slug/"

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "rss"
  isPlainText = false

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[[server.redirects]]
  from = "/rss"
  to = "/rss.xml"
  status = 200
